=== gcistaro/EDUS_2.0/src/InputVariables/input_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "tb_file": {
            "type": "string",
            "default": "",
            "title": "name of the file _tb.dat"
        },
        "decay": {
            "type": "number",
            "default": 0.0,
            "title": "decay rate of the density matrix"
        },
        "decay_units": {
            "type": "string",
            "default": "femtoseconds",
            "enum": [
                "femtoseconds",
                "fs",
                "autime"
            ],
            "title": "Units used for the decay rate of the density matrix"
        },
        "fermienergy": {
            "type": "number",
            "default": 0.0,
            "title": "Fermi energy of the system"
        },
        "fermienergy_units": {
            "type": "string",
            "default": "electronvolt",
            "enum": [
                "electronvolt",
                "joule",
                "Rydberg",
                "auenergy"
            ],
            "title": "Units used for the Fermi energy of the system"
        },
        "coulomb": {
            "type": "boolean",
            "default": false,
            "title": "If true, we go beyond IPA using either RPA or HSEX."
        },
        "method": {
            "type": "string",
            "default": "hsex",
            "enum": ["ipa", "rpa", "hsex"],
            "title": "If ipa, non-interactiong particles are considered. If RPA, we consider only the Hartree term for the interaction. If hsex, both Hartree and screened Fock are taken into account."
        },
        "opengap": {
            "type": "number",
            "default": 0,
            "title": "Gap value, if we want to open more gap"
        },
        "opengap_units": {
            "type": "string",
            "default": "electronvolt",
            "enum": [
                "electronvolt",
                "joule",
                "Rydberg",
                "auenergy"
            ],
            "title": "Units used for the gap we want to open"
        },
        "read_interaction": {
            "type": "boolean",
            "default": false,
            "title": "If true, electron-electron interactions are read from barecoulomb.txt and screencoulomb.txt."
        },
        "bare_file": {
            "type": "string",
            "default": "./barecoulomb.txt",
            "title": "Path of the bare Coulomb interaction"
        },
        "bare_file_hund": {
            "type": "string",
            "default": "./barecoulomb_hund.txt",
            "title": "Path of the bare Coulomb interaction - Hund like"
        },
        "hartree": {
            "type": "boolean",
            "default": true,
            "title": "If false, the Hartree term is skipped in the mean field (with method hsex: screened exchange only)"
        },
        "screen_file": {
            "type": "string",
            "default": "./screencoulomb.txt",
            "title": "Path of the screened Coulomb interaction"
        },
        "epsilon": {
            "type": "number",
            "default": 1.0,
            "title": "Dielectric constant for RK potential"
        },
        "r0": {
            "type": "array",
            "default": [10.0],
            "title": "r0 screening length for RK potential"
        },
        "r0_units": {
            "type": "string",
            "default": "angstrom",
            "enum": [
                "angstrom",
                "nanometers",
                "nm",
                "aulength"
            ],
            "title": "Units for the Time resolution used for propagating Density Matrix"
        },
        "coulomb_model": {
            "type": "string",
            "default": "rytova_keldysh",
            "enum": [
                "rytova_keldysh",
                "vcoul3d"
            ],
            "title": "Coulomb model type"
        },
        "grid": {
            "type": "array",
            "items": {
                "type": "integer"
            },
            "minItems": 3,
            "maxItems": 3,
            "default": [
                10,
                10,
                1
            ],
            "title": "Dimension of the k grid (R as well) used for the simulation"
        },
        "filledbands": {
            "type": "integer",
            "default": 0,
            "title": "Number of filled bands for the simulation (ideally will be either this of fermienergy"
        },
        "dt": {
            "type": "number",
            "default": 0.01,
            "title": "Time resolution used for propagating Density Matrix"
        },
        "gradient_space": {
            "type": "string",
            "default": "R",
            "title": "Space where the gradient with respect to k is evaluated"
        },
        "dt_units": {
            "type": "string",
            "default": "autime",
            "enum": [
                "femtoseconds",
                "fs",
                "autime"
            ],
            "title": "Units for the Time resolution used for propagating Density Matrix"
        },
        "printresolution": {
            "type": "integer",
            "default": 1,
            "title": "Time steps needed to print in hdf5 and observables"
        },
        "printresolution_h5": {
            "type": "integer",
            "default": 0,
            "title": "If > 0, the hdf5 matrices are printed every printresolution_h5 time steps, whether the lasers are on or off"
        },
        "printresolution_pulse": {
            "type": "integer",
            "default": 0,
            "title": "Time steps needed to print in hdf5 and observables during the pulse"
        },
        "initialtime": {
            "type": "number",
            "default": 0.0,
            "title": "Initial time of the simulation"
        },
        "initialtime_units": {
            "type": "string",
            "default": "autime",
            "enum": [
                "femtoseconds",
                "fs",
                "autime"
            ],
            "title": "Units for the Time resolution used for Initial time of the simulation"
        },
        "finaltime": {
            "type": "number",
            "default": 0.0,
            "title": "Final time of the simulation"
        },
        "finaltime_units": {
            "type": "string",
            "default": "autime",
            "enum": [
                "femtoseconds",
                "fs",
                "autime"
            ],
            "title": "Units for the Time resolution used for Final time of the simulation"
        },
        "solver": {
            "type": "string",
            "default": "RK",
            "enum": [
                "RK",
                "AB"
            ],
            "title": "Solver used for time propagation of the Density Matrix"
        },
        "order": {
            "type": "integer",
            "default": 4,
            "title": "Order of the Solver used for time propagation of the Density Matrix"
        },
        "peierls": {
            "type": "boolean",
            "default": true,
            "title": "If true, we propagate the EOM in the Peierls gauge"
        },
        "toprint": {
            "type":  "array",
            "title": "Big quantities that we want to print",
            "minItems": 1,
            "maxItems": 10,
            "default": {
                "DMk_wannier" : "false",
                "DMk_bloch"   : "false",
                "fullH"       : "false",
                "SelfEnergy"  : "false",
                "DM_R"        : "false"
            },
            "items" : {
                "DMk_wannier" : {
                    "type"    : "string",
                    "default" : "false",
                    "title"   : "true if you want to print DM in k, wannier gauge"
                },
                "DMk_bloch"   : {
                    "type"    : "string",
                    "default" : "false",
                    "title"   : "true if you want to print DM in k, bloch gauge"
                },
                "fullH"       : {
                    "type"    : "string",
                    "default" : "false",
                    "title"   : "true if you want to print H=H0+Er in k, wannier gauge"
                },
                "SelfEnergy"  : {
                    "type"    : "string",
                    "default" : "false",
                    "title"   : "true if you want to print the self energy in k, wannier gauge"
                },
                "DM_R"        : {
                    "type"    : "string",
                    "default" : "false",
                    "title"   : "true if you want to print the equilibrium DM in R (Output/DM<rank>.txt, txt)"
                }
            }
        },
        "kpath": {
            "type":  "array",
            "title": "vertex of a path in k space where we want to print the band structure",
            "minItems": 0,
            "maxItems": 100,
            "default": []
        },
        "lasers": {
            "type": "array",
            "title": "description of all the lasers",
            "minItems": 1,
            "maxItems": 10,
            "default" : {
                "type": "object",
                "title": "laser",
                "properties": 
                {
                    "intensity": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Intensity of the laser"
                    },
                    "intensity_units": {
                        "type": "string",
                        "default": "wcm2",
                        "enum": [
                            "wcm2",
                            "auintensity"
                        ],
                        "title": "Units for intensity of the laser"
                    },
                    "frequency": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Frequency of the laser"
                    },
                    "frequency_units": {
                        "type": "string",
                        "default": "electronvolt",
                        "enum": [
                            "electronvolt",
                            "joule",
                            "Rydberg",
                            "auenergy"
                        ],
                        "title": "Units for frequency of the laser"
                    },
                    "wavelength": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Wavelength of the laser"
                    },
                    "wavelength_units": {
                        "type": "string",
                        "default": "nm",
                        "enum": [
                            "angstrom",
                            "nanometers",
                            "nm",
                            "aulength"
                        ],
                        "title": "Units for wavelength of the laser"
                    },
                    "polarization": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "default": 0.0
                        },
                        "title": "Polarization of the laser in cartesian coordinates"
                    },
                    "t0": {
                        "type": "number",
                        "default": 0.0,
                        "title": "initial time of the laser"
                    },
                    "t0_units": {
                        "type": "string",
                        "default": "fs",
                        "enum": [
                            "femtoseconds",
                            "fs",
                            "autime"
                        ],
                        "title": "Units for initial time of the laser"
                    },
                    "cycles": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Number of cycles the sin2 laser last."
                    },
                    "phase": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Phase of the laser"
                    }
                }
            }, 
            "items" : {
                "type": "object",
                "title": "laser",
                "properties": 
                {
                    "intensity": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Intensity of the laser"
                    },
                    "intensity_units": {
                        "type": "string",
                        "default": "wcm2",
                        "enum": [
                            "wcm2",
                            "auintensity"
                        ],
                        "title": "Units for intensity of the laser"
                    },
                    "frequency": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Frequency of the laser"
                    },
                    "frequency_units": {
                        "type": "string",
                        "default": "electronvolt",
                        "enum": [
                            "electronvolt",
                            "joule",
                            "Rydberg",
                            "auenergy"
                        ],
                        "title": "Units for frequency of the laser"
                    },
                    "wavelength": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Wavelength of the laser"
                    },
                    "wavelength_units": {
                        "type": "string",
                        "default": "nm",
                        "enum": [
                            "angstrom",
                            "nanometers",
                            "nm",
                            "aulength"
                        ],
                        "title": "Units for wavelength of the laser"
                    },
                    "polarization": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "default": 0.0
                        },
                        "title": "Polarization of the laser in cartesian coordinates"
                    },
                    "t0": {
                        "type": "number",
                        "default": 0.0,
                        "title": "initial time of the laser"
                    },
                    "t0_units": {
                        "type": "string",
                        "default": "fs",
                        "enum": [
                            "femtoseconds",
                            "fs",
                            "autime"
                        ],
                        "title": "Units for initial time of the laser"
                    },
                    "cycles": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Number of cycles the sin2 laser last."
                    },
                    "phase": {
                        "type": "number",
                        "default": 0.0,
                        "title": "Phase of the laser"
                    }
                }
            }
        }
    }
}

=== gcistaro/EDUS_2.0/ci-test/inputs/Si.json
{
    "tb_file": "/home/sa_m/EDUS_2.0/tb_models/Si",
    "fermienergy": 0, 
    "fermienergy_units" : "electronvolt",
    "coulomb": true,
    "grid": [10,10,10],
    "filledbands" : 1,
    "dt": 0.01, 
    "dt_units" : "femtoseconds",
    "printresolution": 1,
    "printresolution_pulse": 1,
    "initialtime" : 0,
    "initialtime_units" : "femtoseconds",
    "finaltime": 1, 
    "finaltime_units" : "femtoseconds",

    "solver": "RK",
    "order": 4,

    "lasers":
    [
      {
      "intensity": 1e10,
      "intensity_units" : "wcm2",
      "frequency": 10,
      "frequency_units" : "electronvolt",
      "polarization": [1,1,0],
      "cycles" : 1
      }
    ]
  }
